build:
  image: default-bionic
  environment:
    php: 8.1.2
  node:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths: [tests/*]

tools:
  external_code_coverage:
    runs: 6
